FROM python:3.7

# upgrade pip3
RUN  pip install --upgrade pip

RUN pip install ansible

RUN apt-get update && \
    apt-get install --no-install-recommends -y \   
        openssh-server

## end apt installs
RUN apt-get clean && rm -rf /var/lib/apt/lists/*
